### ISSUE TITLE
Where to find the output of "Generate the inference dataset for APC / ATEPC task" ?

### ISSUE THREAD

**Issue by parasd086** [yangheng95/ABSADatasets#18]
When I ran this- 

`from pyabsa.utils.file_utils import generate_inference_set_for_apc 
generate_inference_set_for_apc(dataset_path="/content/dataset")`

I got the output- "Process Finished" but I'm unable to find output inference file.

**Comment by yangheng95** [comment]
Hi, 
the dataset file name should contain the train, test or valid string, please see the existing file names. Once the dataset was processed, its file name will be printed before process finished.

**Comment by parasd086** [comment]
The .txt file which I received output from web browser tool are all "sentences" line after line. Ex-
can you check whether its cancelled completely?
cannot rely on both milk delivery and grocery items.
I get no notification, however the app is really fine
Love this app, but would love it even more if Gantt charts and Calendar view were available on iPhone!

Is this normal?

**Comment by yangheng95** [comment]
Got no idea what are the real problem. The PDT tool should give us several files, including a .txt file that formated as existing apc datasets. It seems your output is not expected. Can you tell us how to reproduce your problem?

**Comment by parasd086** [comment]
I downloaded this repository in my local pc. Then opened the "ABSADatasetPrepareTool.html" file load the csv file(no headers) and assigned the polarity and clicked save. Received 3 outputs as expected- .txt, .csv and .json.

Do I have to install any library or run some files first before working on this web based tool(I have not pip installed PyABSA in my local pc) ?

**Comment by yangheng95** [comment]
Can you provide a small cut of your data, e.g., data before process and behind process.

**Comment by parasd086** [comment]
Sure. Here it is- https://imgur.com/a/uJoMOAO

**Comment by parasd086** [comment]
So, I restarted the web tool and finally got the result in the format- 
Sentence
AspectWord
Polarity

But still unable to get the inference file after running this piece of code-
`from pyabsa.utils.file_utils import generate_inference_set_for_apc generate_inference_set_for_apc(dataset_path="/content/dataset")`

**Comment by yangheng95** [comment]
Hi,

Here are my suggestions. 
make sure your dataset file name dont be confusing, e.g., file name should not contain both 'train' and 'test' string.
use a more detailed dataset_path arg, and it should contain a 'apc' string. Due to distinguish apc datasets and atepc datasets
check your folder if there is the generated inference file, if it exists and doesnt work, please fell free to report.

**Comment by parasd086** [comment]
Hi,

Followed these suggestions, its working now! Thank you.
