### ISSUE TITLE
ABSADatasetPrepareTool.html doesn't work properly

### ISSUE THREAD

**Issue by EgorRazumilov** [yangheng95/ABSADatasets#19]
Hello!     
First of all - thanks for the great repos for solving ABSA problem.     
I have some issue with ABSADatasetPrepareTool: I downloaded and launched it on 3 different browsers (Mozilla, Google, Edge), and in all cases I have this kind of application at startup. 
![image](https://user-images.githubusercontent.com/63121207/153728571-75f406e0-1843-4a78-a023-878b417969f2.png)
None of the buttons responds to pressing.
I don't know HTML and JavaScript at all, so I would be glad if you could help me figure this out.

**Comment by yangheng95** [comment]
Hi, @lpfy I see the same problem but I have no idea how to fix it, can you have a look if possible? Thanks.

**Comment by lpfy** [comment]
Hi @yangheng95 @EgorRazumilov, the data preparation tool was designed by using Vue v2, the CDN load Vue v3 by default now, so I have specified the version for js library loading. It should be working properly now after PR merged.

**Comment by yangheng95** [comment]
Thanks very much! @lpfy

**Comment by yangheng95** [comment]
@EgorRazumilov Please have a test and close this issue if it is done.

**Comment by EgorRazumilov** [comment]
It's working! Thanks!
