### ISSUE TITLE
中文数据集问题

### ISSUE THREAD

**Issue by Syiiiii** [yangheng95/ABSADatasets#22]
请问APC/ATEPC的中文数据集如何手动标注，ABSADatasetPrepareTool貌似无法标注中文数据集，或者有其他标注好的中文数据集推荐吗？万分感谢！

**Comment by yangheng95** [comment]
Please Ref. https://github.com/yangheng95/ABSADatasets/issues/14#issuecomment-999330969

**Comment by Syiiiii** [comment]
> Please Ref. [#14 (comment)](https://github.com/yangheng95/ABSADatasets/issues/14#issuecomment-999330969)

您好，如果按照分词后再用DPT得到的结果和没有分词直接手工标注得到的结果之间有明显的差异吗

**Comment by yangheng95** [comment]
尚未有结论，请您自行测试
