### ISSUE TITLE
ABSADatasetPrepareTool use error

### ISSUE THREAD

**Issue by mnljx** [yangheng95/ABSADatasets#23]
when I used ABSADatasetPrepareTool recently, an unexpected error occurred. But it was working fine when used not long ago. I didn't find out what the problem was. Hope to get your answer. Thank you.
<img width="1070" alt="屏幕截图 2022-05-25 141123" src="https://user-images.githubusercontent.com/106226842/170195263-c0668a11-384e-4ead-be37-c55466c268ab.png">

**Comment by yangheng95** [comment]
Did you clone the latest code? if you did, this may be caused by network error, you can try later or use other network to to this

**Comment by mnljx** [comment]
The version of the tool I am using is the lastest v1.2. And the error is "Uncaught ReferenceError: Vue is not defined". This doesn't look like a problem with my network. It suggests that there is a bug in line 183 of the code as follows
![屏幕截图 2022-05-25 190506](https://user-images.githubusercontent.com/106226842/170249708-c24e4a82-375c-4d8f-87d0-a144f62b86d3.png)
:

**Comment by yangheng95** [comment]
Check the version here: https://github.com/yangheng95/ABSADatasets/blob/f50fd486cc48d88ea714e57fb5f376bed39e21bb/DPT/ABSADatasetPrepareTool.html#L5
And you can try to use a third-party website which deploy this DPT tool:
https://pyabsa.pages.dev

**Comment by mnljx** [comment]
![屏幕截图 2022-05-26 094144](https://user-images.githubusercontent.com/106226842/170398091-82604a77-93c2-4857-bc98-0bd716b52612.png)
The version is correct. I tried https://pyabsa.pages.dev/, and it had the same problem. If your tool is working properly, I guess there may be a reason we don't know. Thank you.

**Comment by yangheng95** [comment]
I test it and it works fine, you can try on other envs to annotate

**Comment by yangheng95** [comment]
Make sure you can access the CDN servers, e.g., https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js 
https://github.com/yangheng95/ABSADatasets/blob/f50fd486cc48d88ea714e57fb5f376bed39e21bb/DPT/ABSADatasetPrepareTool.html#L9

**Comment by mnljx** [comment]
Sorry to bother you again. I tried several times and could not access the CDN servers. Can I save these scripts locally and then use them such as, vue.min.js, jquery, e.g.? Or is there another way to solve this problem? Thank you.

**Comment by mnljx** [comment]
Thanks for your support, I found the solution here. [jsdelivr / jsdelivr](https://github.com/jsdelivr/jsdelivr)
