### ISSUE TITLE
what is mean B-ASP in ATEPC dataset?

### ISSUE THREAD

**Issue by seominseok48349278** [yangheng95/ABSADatasets#24]
What does B-ASP mean in ATEPC dataset?
Some are B-ASP-999 and some are B-ASP sentiments, so what's the difference?

**Comment by yangheng95** [comment]
-999 is used as padding, have no sentiment. B-ASP or I-ASP should not be followed by -999 (Positive, Negative, etc. instead) in any dataset, if you find so, please report.

**Comment by seominseok4834** [comment]
https://github.com/yangheng95/ABSADatasets/blob/v1.2/datasets/atepc_datasets/110.SemEval/114.restaurant14/Restaurants_Train.xml.seg.atepc

55 line It's labeled kitchen B-ASP-999

**Comment by seominseok48349278** [comment]
> -999 is used as padding, have no sentiment. B-ASP or I-ASP should not be followed by -999 (Positive, Negative, etc. instead) in any dataset, if you find so, please report.

https://github.com/yangheng95/ABSADatasets/blob/v1.2/datasets/atepc_datasets/110.SemEval/114.restaurant14/Restaurants_Train.xml.seg.atepc

55 line It's labeled kitchen B-ASP-999

**Comment by seominseok48349278** [comment]
> -999 is used as padding, have no sentiment. B-ASP or I-ASP should not be followed by -999 (Positive, Negative, etc. instead) in any dataset, if you find so, please report.

    <sentence id="1634">
        <text>The food is uniformly exceptional, with a very capable kitchen which will proudly whip up whatever you feel like eating, whether it's on the menu or not.</text>
        <aspectTerms>
            <aspectTerm term="food" polarity="positive" from="4" to="8"/>
            <aspectTerm term="kitchen" polarity="positive" from="55" to="62"/>
            <aspectTerm term="menu" polarity="neutral" from="141" to="145"/>
        </aspectTerms>
        <aspectCategories>
            <aspectCategory category="food" polarity="positive"/>
        </aspectCategories>
    </sentence>

The original dataset looks like this

**Comment by seominseok48349278** [comment]
> -999 is used as padding, have no sentiment. B-ASP or I-ASP should not be followed by -999 (Positive, Negative, etc. instead) in any dataset, if you find so, please report.

I'm sorry, but what does B-ASP mean and I-ASP mean?

**Comment by yangheng95** [comment]
You may need to know sth about IOB annotation, e.g., https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging)

**Comment by seominseok48349278** [comment]
> You may need to know sth about IOB annotation, e.g., https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging)

Now I understand, thank you very much. I'll try and if it doesn't work, I'll ask
