### ISSUE TITLE
##About building Chinese datasets

### ISSUE THREAD

**Issue by caibird2020** [yangheng95/ABSADatasets#30]
Hello blogger, I found that this tool can only build a dataset for English text. When I try to use Chinese text, it cannot mark the aspect words in it.
I would like to ask if you have any tools here suitable for building Chinese datasets！
![image](https://user-images.githubusercontent.com/64406248/181436215-0568b067-47ad-4d08-a31a-24cb88259423.png)

**Comment by yangheng95** [comment]
https://github.com/yangheng95/ABSADatasets/issues/14

**Comment by caibird2020** [comment]
thank you very much！
