### ISSUE TITLE
How Can I Load Unfinished Work - Dataset Prepared Tools

### ISSUE THREAD

**Issue by itsbimaps14** [yangheng95/ABSADatasets#31]
I got 3 files from saving .csv, .txt, and .json. In the documentation .json file is for saving unfinished work. How can i load my unfinished work in Dataset Prepared Tools. I cant find the menu or button for that.

**Comment by yangheng95** [comment]
Hi, @itsbimaps14 !
I am sorry that this tool is shared by a contributor who may be busy responding to this question. I suggest you annotate a split of your data each time. Please note that whether your data is separated into different files or is a sole file, it will be detected automatically in PyABSA.

**Comment by yangheng95** [comment]
Hi @lpfy , I hope you are doing well. Please have a look at this issue if you are willing to.

**Comment by lpfy** [comment]
> I got 3 files from saving .csv, .txt, and .json. In the documentation .json file is for saving unfinished work. How can i load my unfinished work in Dataset Prepared Tools. I cant find the menu or button for that.

Hi @itsbimaps14 @yangheng95 

It might be a bug which prevent button show up, I will try fix it tonight or during weekend.

**Comment by yangheng95** [comment]
Hi @lpfy , Thank you very much,and I made some changes in the dpt tool you may need to know.

**Comment by itsbimaps14** [comment]
> > I got 3 files from saving .csv, .txt, and .json. In the documentation .json file is for saving unfinished work. How can i load my unfinished work in Dataset Prepared Tools. I cant find the menu or button for that.
> 
> Hi @itsbimaps14 @yangheng95
> 
> It might be a bug which prevent button show up, I will try fix it tonight or during weekend.

Thank you so much for the information, will be waiting for the update :)

**Comment by tubagusmakbark** [comment]
Is there update yet ?, have the same issues, can't find button for load unfinished work

**Comment by yangheng95** [comment]
Hi, everyone!
I am sorry that this problem has not been settled. However, we need to respect the contributors who are very busy doing this work voluntarily. Thanks for using DPT and PyABSA.

**Comment by yangheng95** [comment]
Hi @lpfy ，hope you are well , do you have a plan to fix this issue?

**Comment by itsbimaps14** [comment]
Look like there will no update soon or

**Comment by itsbimaps14** [comment]
It looks like there will be no updates on this issue, so I will close it as not planned. Thanks all.
