### ISSUE TITLE
使用标注后的数据进行训练，报错 RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by L897776** [yangheng95/ABSADatasets#36]
感谢您开源pyabsa和对应的标注工具
我尝试用DPT工具进行标注，发现如果给一个句子标注两个方面词，方面词后面不是positive/negative,而是-999
参考
[https://github.com/yangheng95/ABSADatasets/blob/v1.2/DPT/custom.apc.train.txt.atepc](url)
第一句，电池后面是-999
第二句，iphone13后面是-999

而我使用下面chinese中的数据集进行训练不会报错
[https://github.com/yangheng95/ABSADatasets/tree/v1.2/datasets/atepc_datasets/102.Chinese](url)

进一步观察，我发现这些训练集都是一个句子只标注一个方面词，不会出现上面一个句子标注两个方面词的问题

关于错误 RuntimeError: CUDA error: device-side assert triggered
我尝试在搜索引擎上寻找答案，大部分结果是说label的值对应不上会造成这个问题

不知道标注-999是否会影响到训练，希望得到您的解答

下面是我尝试从`checkpoint`上开始使用自己标注的`233.comment`开始训练的代码

    import random
    
    from pyabsa.functional import ATEPCModelList
    from pyabsa.functional import Trainer, ATEPCTrainer
    from pyabsa.functional import ABSADatasetList
    from pyabsa.functional import ATEPCConfigManager
    
    atepc_config_chinese = ATEPCConfigManager.get_atepc_config_chinese()
    atepc_config_chinese.model = ATEPCModelList.FAST_LCF_ATEPC
    atepc_config_chinese.evaluate_begin = 0
    atepc_config_chinese.pretrained_bert = 'bert-base-chinese'
    atepc_config_chinese.log_step = -1
    atepc_config_chinese.l2reg = 1e-5
    atepc_config_chinese.num_epoch = 5
    atepc_config_chinese.seed = random.randint(1, 100)
    atepc_config_chinese.use_bert_spc = True
    atepc_config_chinese.cache_dataset = False
    
    checkpoint_path = ATEPCCheckpointManager.get_checkpoint(checkpoint='chinese')
    
    aspect_extractor = Trainer(config=atepc_config_chinese,
                               from_checkpoint=checkpoint_path,                           
                               dataset='./233.comment',
                               path_to_save='./pt_chinese', # 保存路径
                               checkpoint_save_mode=1,
                               auto_device=True
                               ).load_trained_model()

**Comment by yangheng95** [comment]
你的数据是存在几个标签？另外请不要犹豫提供全部控制台输出帮助定位问题

**Comment by yangheng95** [comment]
多个aspect的标注结果会在训练前拆分成多个样本，不影响实际训练效果。如果你的数据标签数量与checkpoint中的不同则会出现这个问题。可以试试不基于checkpoint重新训练

**Comment by L897776** [comment]
> 多个aspect的标注结果会在训练前拆分成多个样本，不影响实际训练效果。如果你的数据标签数量与checkpoint中的不同则会出现这个问题。可以试试不基于checkpoint重新训练

感谢您的回复
根据您的提示，我刚才看了下我的标注数据有Positive/Neutral/Negative三类标签，对应我使用的
`checkpoint_path = ATEPCCheckpointManager.get_checkpoint(checkpoint='chinese')`
或许它只有Positive/Negative两类标签？造成了这个问题

**Comment by yangheng95** [comment]
chinese并不会比multilingual好很多，你可以时使用multilingual代替chinese
