### ISSUE TITLE
关于框架数据集来源的问题

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/ABSADatasets#39]
1. pyabsadataset里面有yelp数据集进行方面情感分析，我根据数据集的地址进入了作者的github，发现找不到这个数据集，请问这个数据集是来自于哪篇论文呢？
2. yelp数据集中是哪方面的评论（酒店？餐厅？还是其他的）？

**Comment by yangheng95** [comment]
这是作者收集，委托我上传的数据集。具体细节我不了解，但应该是餐厅评论

**Comment by yaoysyao** [comment]
> 这是作者收集，委托我上传的数据集。具体细节我不了解，但应该是餐厅评论

好的，谢谢
