### ISSUE TITLE
How to proceed after using the annotation tool

### ISSUE THREAD

**Issue by Ajith-Shenoy** [yangheng95/ABSADatasets#41]
Hey Yang and team,
Working on a ABSA task using custom dataset.
I have managed to generate 3 files using the web tool, and now have 
- ABSADataWorkFile.json
- ABSATrainingSet.txt
- SATrainingSet.csv

How can i procced further ? Couldnt reliable find the steps to convert this to Generate the inference dataset for APC / ATEPC task.
also what should the folder structure to be in colab to access this custom dataset for training ?
using 1.16.27

**Comment by yangheng95** [comment]
Sorry for my late reply. Please run this [script](https://github.com/yangheng95/ABSADatasets/blob/v2.0/test.py) to convet your datasets. You can paste your data into the provided custom dataset folder to proceed on training.
