### ISSUE TITLE
How to create tags ($T$) for my custom data?

### ISSUE THREAD

**Issue by Winnieliu0504** [yangheng95/ABSADatasets#42]
I used the `make_absa_dataset` code to annotate my data and the result showed like this for example:

The case is ok but....
case
Positive

What should I do to create tags ($T$) for the result like this?

The $T$ is ok but...
case
Positive

**Comment by yangheng95** [comment]
It is a bug, please update and retry.

**Comment by Winnieliu0504** [comment]
I cloned the ABSADataset github again and retried the `make_absa_dataset` code again but it is not working.
Which version should I get for the updated one? Thanks!

**Comment by yangheng95** [comment]
update pyabsa. pip install pyabsa -U
