### ISSUE TITLE
Is $T$ output APC is correct for auto annotated dataset?

### ISSUE THREAD

**Issue by farrelarrizal** [yangheng95/ABSADatasets#47]
Hi, thanks for your great code!

I was trying to auto-annotate my dataset using the ``make_ABSA_dataset`` function, but after completely processing my dataset I think the output is not the same as you mentioned in the readme.md.

In your readme said that the output ``.APC`` like this :
Cool sanctuary with detailed stonework and tons of ``$T$`` . You can feed them if you buy bananas on site ( or you can bring your own ) , but avoid adult monkeys because they are more aggressive and do not like being teased .
monkeys
Positive

But the output from the function actually is:
Cool sanctuary with detailed stonework and tons of **monkeys ``$T$``** . You can feed them if you buy bananas on site ( or you can bring your own ) , but avoid adult monkeys because they are more aggressive and do not like being teased .
**monkeys**
Positive

so my question is which one is the correct format? the upside or downside one?

![messageImage_1681264566934](https://user-images.githubusercontent.com/72312914/231329419-aec1083d-7206-40df-aab6-4cb54a787d92.jpg)

if the first one is correct I assume that the incorrect syntax as marked below picture, what do you think?
![Screenshot_5](https://user-images.githubusercontent.com/72312914/231329361-cd84149f-e9bb-40d4-9826-57fc083a8727.png)

Thankyou!

**Comment by farrelarrizal** [comment]
what do you think if I do this?

![image](https://user-images.githubusercontent.com/72312914/231940261-4018387e-7a63-49cd-b6b9-b644c309bfbb.png)

**Comment by farrelarrizal** [comment]
Here is the apc result
![Screenshot_6](https://user-images.githubusercontent.com/72312914/231941298-6497273c-f4f9-4d85-b31d-4e301bd2c119.png)

**Comment by yangheng95** [comment]
Sorry for my late reply. I may fix this later, you can try your solution and report if it works, thank you very much!

**Comment by yangheng95** [comment]
I also update 2.2.3 version, you can try if it works

**Comment by farrelarrizal** [comment]
Thanks it works for me
